/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Teams } from "./Teams";
import { TeamsCountArgs } from "./TeamsCountArgs";
import { TeamsFindManyArgs } from "./TeamsFindManyArgs";
import { TeamsFindUniqueArgs } from "./TeamsFindUniqueArgs";
import { CreateTeamsArgs } from "./CreateTeamsArgs";
import { UpdateTeamsArgs } from "./UpdateTeamsArgs";
import { DeleteTeamsArgs } from "./DeleteTeamsArgs";
import { Departments } from "../../departments/base/Departments";
import { TeamsService } from "../teams.service";
@graphql.Resolver(() => Teams)
export class TeamsResolverBase {
  constructor(protected readonly service: TeamsService) {}

  async _teamsItemsMeta(
    @graphql.Args() args: TeamsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Teams])
  async teamsItems(@graphql.Args() args: TeamsFindManyArgs): Promise<Teams[]> {
    return this.service.teamsItems(args);
  }

  @graphql.Query(() => Teams, { nullable: true })
  async teams(
    @graphql.Args() args: TeamsFindUniqueArgs
  ): Promise<Teams | null> {
    const result = await this.service.teams(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Teams)
  async createTeams(@graphql.Args() args: CreateTeamsArgs): Promise<Teams> {
    return await this.service.createTeams({
      ...args,
      data: {
        ...args.data,

        department: args.data.department
          ? {
              connect: args.data.department,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Teams)
  async updateTeams(
    @graphql.Args() args: UpdateTeamsArgs
  ): Promise<Teams | null> {
    try {
      return await this.service.updateTeams({
        ...args,
        data: {
          ...args.data,

          department: args.data.department
            ? {
                connect: args.data.department,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Teams)
  async deleteTeams(
    @graphql.Args() args: DeleteTeamsArgs
  ): Promise<Teams | null> {
    try {
      return await this.service.deleteTeams(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Departments, {
    nullable: true,
    name: "department",
  })
  async getDepartment(
    @graphql.Parent() parent: Teams
  ): Promise<Departments | null> {
    const result = await this.service.getDepartment(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
