/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Resources } from "./Resources";
import { ResourcesCountArgs } from "./ResourcesCountArgs";
import { ResourcesFindManyArgs } from "./ResourcesFindManyArgs";
import { ResourcesFindUniqueArgs } from "./ResourcesFindUniqueArgs";
import { DeleteResourcesArgs } from "./DeleteResourcesArgs";
import { ResourcesService } from "../resources.service";
@graphql.Resolver(() => Resources)
export class ResourcesResolverBase {
  constructor(protected readonly service: ResourcesService) {}

  async _resourcesItemsMeta(
    @graphql.Args() args: ResourcesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Resources])
  async resourcesItems(
    @graphql.Args() args: ResourcesFindManyArgs
  ): Promise<Resources[]> {
    return this.service.resourcesItems(args);
  }

  @graphql.Query(() => Resources, { nullable: true })
  async resources(
    @graphql.Args() args: ResourcesFindUniqueArgs
  ): Promise<Resources | null> {
    const result = await this.service.resources(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Resources)
  async deleteResources(
    @graphql.Args() args: DeleteResourcesArgs
  ): Promise<Resources | null> {
    try {
      return await this.service.deleteResources(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
